apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blackbox-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blackbox-exporter
subjects:
  - kind: ServiceAccount
    name: blackbox-exporter-service-account
    namespace: redhat-rhoam-middleware-monitoring-operator
userNames:
  - system:serviceaccount:application-monitoring:blackbox-exporter-service-account
