apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-application-operator
  name: {{ .PrometheusOperatorName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-application-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-application-operator
    spec:
      containers:
        - args:
            - --kubelet-service=kube-system/kubelet
            - -log-level=warn
            - --prometheus-config-reloader={{ .ImagePrometheusConfigReloader }}:{{ .ImageTagPrometheusConfigReloader }}
            - --prometheus-instance-namespaces={{ .PrometheusInstanceNamespaces }}
            - --alertmanager-instance-namespaces={{ .AlertmanagerInstanceNamespaces }}
            - --thanos-ruler-instance-namespaces={{ .Namespace }}
          image: {{ .ImagePrometheusOperator }}
          name: prometheus-application-operator
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext: {}
      serviceAccountName: prometheus-operator
